language: ruby
rvm:
- 2.2.1
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['HEROKU_API_KEY'] %>
  run:
    - 'rake db:migrate'
  app: foosy
  on:
    repo: ZuzannaSt/foosy
before_script:
- cp config/database.yml.travis config/database.yml
- mysql -e 'create database travis_ci_test'
- RAILS_ENV=test bundle exec rake db:migrate --trace
